name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20.5.1'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Set IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Whitelist runner IP
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.EC2_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGET_DIR }}
          SOURCE: out
      - name: Revoke runner IP
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.EC2_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
