name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20.5.1'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Set Runner IP
        id: ip
        run: |
          {
            echo 'ipv4=<<EOF'
            curl https://api.ipify.org
            echo EOF
          } >> $GITHUB_OUTPUT
      - name: Read IP
        env:
          THE_IP: ${{ steps.ip.outputs.ipv4 }}
        run: echo "The ipv4 is $THE_IP"
