name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20.5.1'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGET_DIR }}
          SOURCE: out
